# Configuration file for Action Recognition Training

# Default Data Configuration
data:
  root_dir: "/dtu/datasets1/02516/ucf101_noleakage"
  dataset_type: "frame_image"  # Options: "frame_image", "frame_video"
  batch_size: 16
  num_workers: 4
  image_size: [112, 112]  # [height, width]
  n_sampled_frames: 10
  stack_frames: true
  augment: true

# Default Model Configuration
model:
  model_type: "single_frame"  # Options: "single_frame", "early_fusion", "late_fusion", "CNN3D"
  num_classes: 10
  num_frames: 10

# Default Training Configuration
training:
  learning_rate: 0.001
  weight_decay: 0.0001
  max_epochs: 80
  accelerator: "auto"  # Options: "auto", "gpu", "cpu", "mps"
  devices: 1
  precision: "32"  # Options: "16", "32", "bf16"
  patience: 40  # For early stopping

# Default Logging and Checkpoints Configuration
logging:
  experiment_name: "action_recognition"
  log_dir: "experiments"
  wandb:
    project: "action-recognition"
    entity: null  # Set to your wandb username/team if needed
    tags: []
    notes: ""
    offline: false
  
# Default Reproducibility Configuration
seed: 42


hydra:
  run:
    # Unified per-run working directory: experiments/<model>/<date>/<time>
    dir: ${logging.log_dir}/${model.model_type}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    # Where multiruns land (kept separate to avoid mixing with single runs)
    dir: ${logging.log_dir}/${model.model_type}/multiruns/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    chdir: true
  output_subdir: .hydra
