# Configuration file for Action Recognition Training

# Data Configuration
data:
  root_dir: "data/ufc10"
  dataset_type: "frame_image"  # Options: "frame_image", "frame_video"
  batch_size: 16
  num_workers: 4
  image_size: [112, 112]  # [height, width]
  n_sampled_frames: 10
  stack_frames: true
  augment: true

# Model Configuration
model:
  model_type: "single_frame"  # Options: "single_frame", "early_fusion", "late_fusion", "CNN3D"
  num_classes: 10
  num_frames: 10

# Training Configuration
training:
  learning_rate: 0.001
  weight_decay: 0.0001
  max_epochs: 30
  accelerator: "auto"  # Options: "auto", "gpu", "cpu", "mps"
  devices: 1
  precision: "32"  # Options: "16", "32", "bf16"
  patience: 10  # For early stopping

# Logging and Checkpoints
logging:
  experiment_name: "action_recognition"
  log_dir: "experiments"
  
# Reproducibility
seed: 42

# Action Classes (for reference)
# classes:
#   0: "BodyWeightSquats"
#   1: "HandstandPushups"
#   2: "HandstandWalking"
#   3: "JumpingJack"
#   4: "JumpRope"
#   5: "Lunges"
#   6: "PullUps"
#   7: "PushUps"
#   8: "TrampolineJumping"
  # 9: "WallPushups"

hydra:
  run:
    # Unified per-run working directory: experiments/<model>/<date>/<time>
    dir: ${logging.log_dir}/${model.model_type}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    # Where multiruns land (kept separate to avoid mixing with single runs)
    dir: ${logging.log_dir}/${model.model_type}/multiruns/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    chdir: true
  output_subdir: .hydra
