# @package _global_

# Override default config for early fusion model experiments
defaults:
  - config

model:
  model_type: early_fusion

data:
  dataset_type: frame_video
  batch_size: 32

training:
  max_epochs: 30

logging:
  experiment_name: early_fusion_experiment
