# @package _global_

# Override default config for single frame model experiments
defaults:
  - config

model:
  model_type: single_frame_model

data:
  dataset_type: frame_image
  batch_size: 32

training:
  max_epochs: 30

logging:
  experiment_name: single_frame_experiment
