# @package _global_

# Override default config for late fusion model experiments
defaults:
  - config

model:
  model_type: late_fusion

data:
  dataset_type: frame_image
  batch_size: 32

training:
  max_epochs: 30

logging:
  experiment_name: late_fusion_experiment
