# @package _global_

# Override default config for late fusion model experiments
defaults:
  - config

model:
  model_type: late_fusion

data:
  dataset_type: frame_video
  batch_size: 32

training:
  max_epochs: 200

logging:
  experiment_name: late_fusion_experiment
  wandb:
    project: "action-recognition"
    entity: null
    tags: ["late_fusion", "video"]
    notes: "Late fusion action recognition experiment"
    offline: false
