# @package _global_

# Override default config for C3D experiments
defaults:
  - config

model:
  model_type: C3D

data:
  dataset_type: frame_video
  batch_size: 8
  n_sampled_frames: 16

training:
  max_epochs: 50

logging:
  experiment_name: c3d_experiment
